config:
  target: http://localhost:8000
  phases:
    - duration: 60
      arrivalRate: 5
  plugins:
    expect: {}
scenarios:
  - name: Create Category and Product
    flow:
      # Step 1: Create a Category
      - post:
          url: /categories
          headers:
            Content-Type: application/json
          json:
            name: "Category_Example_{{ $uuid }}" # Unique category name
          capture:
            - json: "$.id"
              as: category_id # Save the category ID for use in product creation
          expect:
            statusCode: 201

      - function: |
          if (!vars.category_id) {
            throw new Error('Failed to capture category_id, cannot create product.');
          }

      # Step 2: Create a Product
      - post:
          url: /products
          headers:
            Content-Type: application/json
          json:
            name: "Product_Example_{{ $uuid }}" # Unique product name
            description: "This is a test product linked to a category."
            price: 49.99
            stock: 100
            category_id: "{{ category_id }}" # Use the captured category_id
          capture:
            - json: "$.id"
              as: product_id # Save the product ID for future use if needed
          expect:
            statusCode: 201

      # Optional Step: Validate Product Creation (Optional)
      - function: |
          if (!vars.product_id) {
            throw new Error('Failed to capture product_id after product creation.');
          }
      - get:
          url: /products/{{ product_id }}
          headers:
            Content-Type: application/json
          expect:
            statusCode: 200
