config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 10
  plugins:
    cloud:
      apiKey: 'a9_zQjpJafHeFguNo_CRSgquYAD9qjUtb0A'
scenarios:
  - flow:
      - get:
          url: "/products"
