config:
  target: "http://localhost:8000"
  phases:
    - duration: 60
      arrivalRate: 10
scenarios:
  - flow:
      # Create Category
      - post:
          url: "/categories"
          json:
            name: "Initial Category"
          capture:
            - json: "$.id"
              as: "category_id"
      # Update Category
      - put:
          url: "/categories/{{ category_id }}"
          json:
            name: "Updated Category Name"

      # Create Product
      - post:
          url: "/products"
          json:
            name: "Initial Product"
            description: "Initial Description"
            price: 19.99
            stock: 10
            category_id: "{{ category_id }}"
          capture:
            - json: "$.id"
              as: "product_id"
      # Update Product
      - put:
          url: "/products/{{ product_id }}"
          json:
            name: "Updated Product"
            price: 99.99
            stock: 20
            description: "Updated Description"
            category_id: "{{ category_id }}"

      # Create Customer
      - post:
          url: "/customers"
          json:
            name: "Initial Customer"
            email: "customer@example.com"
            phone: "1234567890"
          capture:
            - json: "$.id"
              as: "customer_id"
      # Update Customer
      - put:
          url: "/customers/{{ customer_id }}"
          json:
            name: "Updated Customer"
            email: "updated@example.com"
            phone: "9876543210"

      # Create Order
      - post:
          url: "/orders"
          json:
            customer_id: "{{ customer_id }}"
            items:
              - product_id: "{{ product_id }}"
                quantity: 2
                price: 19.99
          capture:
            - json: "$.order_id"
              as: "order_id"
      # Update Order
      - put:
          url: "/orders/{{ order_id }}"
          json:
            customer_id: "{{ customer_id }}"
            items:
              - product_id: "{{ product_id }}"
                quantity: 3
                price: 29.99

      # Delete Entities
      - delete:
          url: "/orders/{{ order_id }}"
      - delete:
          url: "/customers/{{ customer_id }}"
      - delete:
          url: "/products/{{ product_id }}"
      - delete:
          url: "/categories/{{ category_id }}"
