config:
  target: "http://localhost:8000"
  phases:
    - duration: 60
      arrivalRate: 5
scenarios:
  - name: Full API Test for pythonArtillery
    flow:
      - post:
          url: "/categories"
          json:
            name: "Electronics"
      - post:
          url: "/products"
          json:
            name: "Smartphone"
            description: "A high-end smartphone"
            price: 999.99
            stock: 50
            category_id: 1
      - post:
          url: "/customers"
          json:
            name: "John Doe"
            email: "john.doe@example.com"
            phone: "123-456-7890"
      - post:
          url: "/orders"
          json:
            customer_id: 1
            items:
              - product_id: 1
                quantity: 2
                price: 999.99
      - get:
          url: "/orders/detailed"
      - delete:
          url: "/orders/1"
      - delete:
          url: "/customers/1"
      - delete:
          url: "/products/1"
      - delete:
          url: "/categories/1"
