config:
  target: 'http://localhost:8000'  # Replace with your FastAPI app URL
  phases:
    - duration: 60  # Duration of the test
      arrivalRate: 10  # Requests per second
    - duration: 180  # Duration of the second phase
      arrivalRate: 20  # Increased requests per second
    - duration: 120
      arrivalRate: 50

scenarios:
  # Scenario 1: Create a product and retrieve it
  - name: "Create and Retrieve Products"
    flow:
      - post:
          url: '/products'
          json:
            name: "Test Product"
            price: 100.0
            stock: 50
      - get:
          url: '/products'
    
  # Scenario 2: Create a customer and retrieve them
  - name: "Create and Retrieve Customers"
    flow:
      - post:
          url: '/customers'
          json:
            name: "Test Customer"
            email: "customer@example.com"
            phone: "123-456-7890"
      - get:
          url: '/customers'
    
  # Scenario 3: Create an order and retrieve it
  - name: "Create and Retrieve Orders"
    flow:
      - post:
          url: '/orders'
          json:
            customer_id: 1  # Use a valid customer ID
            items:
              - product_id: 1  # Use a valid product ID
                quantity: 2
                price: 100.0
      - get:
          url: '/orders/1'  # Retrieve the order by its ID
    
  # Scenario 4: Update a product and retrieve it
  - name: "Update Product and Retrieve"
    flow:
      - put:
          url: '/products/1'  # Replace 1 with an existing product ID
          json:
            name: "Updated Product"
            price: 150.0
            stock: 60
      - get:
          url: '/products/1'

  # Scenario 5: Update a customer and retrieve it
  - name: "Update Customer and Retrieve"
    flow:
      - put:
          url: '/customers/1'  # Replace 1 with an existing customer ID
          json:
            name: "Updated Customer"
            email: "updatedcustomer@example.com"
            phone: "987-654-3210"
      - get:
          url: '/customers/1'

  # Scenario 6: Delete a product
  - name: "Delete Product"
    flow:
      - delete:
          url: '/products/1'  # Replace 1 with an existing product ID
    
  # Scenario 7: Delete a customer
  - name: "Delete Customer"
    flow:
      - delete:
          url: '/customers/1'  # Replace 1 with an existing customer ID
    
  # Scenario 8: Delete an order
  - name: "Delete Order"
    flow:
      - delete:
          url: '/orders/1'  # Replace 1 with an existing order ID
